---
title: Components
description: Removes certain Windows components
privilege: TrustedInstaller
actions:

  # ------------------------- NOTES ------------------------- #
  
  # - Some of this is redundant with packages.yml
  
  # ----------------------- END NOTES ----------------------- #

    # ---------- Windows Defender
  - !writeStatus: {status: 'Removing Windows Defender'}
  - !taskKill: {name: 'NisSrv'}
  - !taskKill: {name: 'SecurityHealthHost'}
  - !taskKill: {name: 'SecurityHealthService'}
  - !taskKill: {name: 'SecurityHealthSystray'}
  - !taskKill: {name: 'SkypeBackgroundHost'}
  - !taskKill: {name: 'MsMpEng'}
  - !taskKill: {name: 'msiexec'}
  - !file: {path: 'C:\Windows\System32\smartscreen.exe'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthSystray.exe'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthService.exe'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthAgent.dll'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthHost.exe'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthSSO.dll'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthCore.dll'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthProxyStub.dll'}
  - !file: {path: 'C:\Windows\System32\SecurityHealthUdk.dll'}
  - !file: {path: 'C:\Program Files\Windows Defender', weight: 30}
  - !file: {path: 'C:\ProgramData\Microsoft\Windows Defender', weight: 30}
  - !file: {path: 'C:\Program Files (x86)\Windows Defender', weight: 30}
  - !file: {path: 'C:\Windows\System32\drivers\WdNisDrv.sys'}
  - !file: {path: 'C:\Program Files\Windows Defender Advanced Threat Protection'}
  - !file: {path: 'C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection'}

    # Remove Security Center startup item
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'SecurityHealth', operation: delete}

    # ---------- Microsoft Edge
  - !writeStatus: {status: 'Removing Microsoft Edge', option: 'uninstall-edge'}
  - !run:
    exe: 'C:\Windows\AtlasModules\Tools\NSudoLG.exe'
    args: '-U:E -P:E -Wait -ShowWindowMode:Hide powershell.exe -NoP -EP Unrestricted -File "C:\Users\Default\Desktop\Atlas\1. Software\Remove Edge.ps1" -AMEWizard'
    wait: true
    option: 'uninstall-edge'
    # AppX uninstallation in the script seems to fail with NSudo, therefore it's not used and AME Wizard is used instead
  - !appx: {name: 'Microsoft.MicrosoftEdge_8wekyb3d8bbwe', type: family, option: 'uninstall-edge'}

    # ---------- OneDrive
  - !writeStatus: {status: 'Removing OneDrive'}
  - !taskKill: {name: 'OneDriveStandaloneUpdater'}
  - !taskKill: {name: 'OneDriveSetup'}
  - !taskKill: {name: 'OneDrive*'}

  - !cmd: {command: '%windir%\SysWOW64\OneDriveSetup.exe /uninstall'}
  - !file: {path: 'C:\OneDriveTemp'}

    # ---------- Update Health Tools
  - !writeStatus: {status: 'Removing Update Health Tools'}
  - !powerShell: {command: 'Uninstall-MsiexecByName "Microsoft Update Health Tools"'}

    # ---------- PC Health Check
  - !writeStatus: {status: 'Removing PC Health Check'}
  - !powerShell: {command: 'Uninstall-MsiexecByName "Windows PC Health Check"'}

    # This could be done in config.yml, however on the off-chance that
    # the Playbook fails or the system shuts down, we want the users converted
    # before potentially making any MS Accounts inoperable in packages.yml.
  - !run:
    exeDir: true
    exe: 'CONVERTUSERS.cmd'
    weight: 30