---
title: Disable/Disallow Offline Files
description: Disables Offline Files to prevent 'mobsync.exe' from running in the background
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\NetCache'
    value: 'Enabled'
    data: '0'
    type: REG_DWORD
