---
title: Hide Settings Pages
description: Hides unnecessary Settings pages, which are either not recommended to use or disabled within the registry
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'SettingsPageVisibility'
    data: 'hide:tabletmode;crossdevice;mobile-devices;maps;sync;easeofaccess-magnifier;privacy-general;privacy-feedback;privacy-activityhistory;privacy-location;privacy-callhistory;privacy-automaticfiledownloads;backup;findmydevice;'
    type: REG_SZ
