---
title: Disable Core Isolation
description: Disables Core Isolation (VBS) based on the user's options
privilege: TrustedInstaller
actions:
  - !cmd:
    command: 'echo ^& "%windir%\AtlasDesktop\7. Security\Core Isolation (VBS)\Current Configuration.ps1" -DisableAllVBS > script.ps1 & powershell -NoP -File script.ps1'
    exeDir: true
    wait: true
    option: 'vbs-disable'
