---
title: Configure Power Settings
description: Executes script to configure power settings for the best performance, especially focusing on the lowest latency e.g. by reducing any potential jitter
privilege: TrustedInstaller
actions:
  - !run:
    exe: 'C:\Users\Default\Desktop\Atlas\3. Configuration\1. General Configuration\Power\Power Saving\Disable Power Saving.cmd'
    args: '/setup'
    weight: 20
    option: 'disable-power-saving'
