---
title: Configure Power Settings
description: Executes script to configure power settings for the best performance, especially focusing on the lowest latency e.g. by reducing any potential jitter
actions:
    # Disable Power Saving features
  - !run: {exe: 'powercfg.exe', args: '/restoredefaultpowerschemes'}
  - !cmd:
    command: '"AtlasDesktop\3. General Configuration\Power\Power-saving\Disable Power-saving.cmd" -Silent'
    exeDir: true
    wait: true
    weight: 20
    option: 'disable-power-saving'

    # Disable Fast Startup
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power'
    value: 'HiberbootEnabled'
    data: '0'
    type: REG_DWORD

    # Disable Hibernation
    # Disabling makes NTFS accessible outside of Windows
  - !cmd:
    command: '"AtlasDesktop\3. General Configuration\Power\Hibernation\Disable Hibernation (default).cmd" /silent'
    exeDir: true
    wait: true
    weight: 20
    option: 'disable-hibernation'
