---
title: Configure Quick Settings in Notification Center
description: Configures Quick Settings in Notification Center for QoL
privilege: TrustedInstaller
actions:
    # Unpin all quick action shortcuts by default
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.WiFi'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.AllSettings'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.BlueLightReduction'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.AvailableNetworks'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Location'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Connect'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.QuietHours'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.ScreenClipping'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Vpn'
    data: ''
    type: REG_NONE
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Project'
    data: ''
    type: REG_NONE
