---
title: Configure Start Menu
description: Configures the Start Menu's settings
privilege: TrustedInstaller
actions:
    # Configure start menu settings
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoStartMenuMFUprogramsList'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'HideRecentlyAddedApps'
    data: '1'
    type: REG_DWORD
