
title: Configure Start Menu
description: Configures the Start Menu's layout and settings
privilege: TrustedInstaller
actions:
    # Lock start menu layout and disable tiles
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'StartLayoutFile'
    data: 'C:\Windows\layout.xml'
    type: REG_EXPAND_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'LockedStartLayout'
    data: '1'
    type: REG_DWORD

    # Configure start menu settings
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoStartMenuMFUprogramsList'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'HideRecentlyAddedApps'
    data: '1'
    type: REG_DWORD