---
title: Disable Immersive Control Panel Tips
description: Disables Settings (Immersive Control Panel) tips for QoL, as most of the time, they only get in the way
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\Settings\AllowOnlineTips'
    value: 'value'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'AllowOnlineTips'
    data: '0'
    type: REG_DWORD
