blank_issues_enabled: false
contact_links:
  - name: General questions
    url: https://discord.com/servers/atlas-795710270000332800
    about: Please join our Discord server for general inquiries.
  - name: General questions (if you do not have Discord)
    url: https://github.com/Atlas-OS/Atlas/discussions/new
    about: In case if you don't have discord, use this.
  - name: Call of Duty Modern Warfare II fix
    url: https://github.com/Atlas-OS/Atlas/discussions/362
    about: Have problems running COD Modern Warfare II? Follow this guide.
