blank_issues_enabled: false
contact_links:
  - name: General questions
    url: https://discord.com/servers/atlas-795710270000332800
    about: Please join our Discord server for general inquiries.
  - name: General questions (if you do not have Discord)
    url: https://forum.atlasos.net
    about: In case you do not have Discord, use this.
