blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://discord.com/servers/atlas-795710270000332800
    about: Please join our Discord for general inquiries.
  - name: Call of Duty Modern Warfare Fix
    url: https://github.com/Atlas-OS/Atlas/issues/353#issuecomment-1336430877
    about: have "Windows 10 20H2 is not supported"? follow this guide.
