---
title: Status In AME Wizard For The Security Category
description: Displays a status in AME Wizard for a specified category
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Running security tweaks'}