---
title: Configure Content Delivery Manager
description: Configures Content Delivery Manager to not download any normally pre-installed applications ( e.g. bloat like Disney+) mostly for QoL, but also for privacy.
privilege: TrustedInstaller
actions:
    # Disable Content Delivery Manager
    # Disable pre-installed applications
    # Disable Windows welcome experience
    # Disable suggested content in Immersive Control Panel
    # Disable fun facts, tips, tricks on Windows Spotlight
    # Disable start menu suggestions
    # Disable get tips, tricks, and suggestions as you use Windows
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'ContentDeliveryAllowed'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'OemPreInstalledAppsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'PreInstalledAppsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'PreInstalledAppsEverEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SilentInstalledAppsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-310093Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338393Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-353694Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-353696Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338387Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'RotatingLockScreenOverlayEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338388Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SystemPaneSuggestionsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338389Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SoftLandingEnabled'
    data: '0'
    type: REG_DWORD