---
title: Disable SmartScreen
description: SmartScreen is a security feature for warning users about the dangers of executing certain files from third party sources, and it is disabled for QoL.
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost'
    value: 'EnableWebContentEvaluation'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost'
    value: 'PreventOverride'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System'
    value: 'EnableSmartScreen'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'
    value: 'SmartScreenEnabled'
    data: 'Off'
    type: REG_SZ
