---
title: Configuration
description: Applies the Atlas configuration
privilege: TrustedInstaller
actions:
    # -------------------- Registry Portion --------------------

  - !writeStatus: {status: 'Modifying registry settings'}
    # Disable Performance Track (PerfTrack)
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}'
    value: 'ScenarioExecutionEnabled'
    data: '0'
    type: REG_DWORD

    # Disable advertising info
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo'
    value: 'Enabled'
    data: '0'
    type: REG_DWORD

    # Disable Bluetooth advertising
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\current\device\Bluetooth'
    value: 'AllowAdvertising'
    data: '0'
    type: REG_DWORD

    # Disable KMS client online AVS validation
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform'
    value: 'NoGenTicket'
    data: '1'
    type: REG_DWORD

    # Disable Windows Feedback
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Siuf\Rules'
    value: 'NumberOfSIUFInPeriod'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Siuf\Rules'
    value: 'PeriodInNanoSeconds'
    operation: delete
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection'
    value: 'DoNotShowFeedbackNotifications'
    data: '1'
    type: REG_DWORD

    # Disable location tracking
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\FindMyDevice'
    value: 'AllowFindMyDevice'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\FindMyDevice'
    value: 'LocationSyncEnabled'
    data: '0'
    type: REG_DWORD

    # Hide meet now button on taskbar
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'HideSCAMeetNow'
    data: '1'
    type: REG_DWORD

    # Hide task view button on taskbar
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MultiTaskingView\AllUpView'
    value: 'Enabled'
    operation: delete
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'ShowTaskViewButton'
    data: '0'
    type: REG_DWORD

    # Disable news and interests on taskbar
    # Explorer immediately reset ShellFeedsTaskbarViewMode otherwise
  - !taskKill:
    name: 'explorer'
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds'
    value: 'ShellFeedsTaskbarViewMode'
    data: '2'
    type: REG_DWORD
    operation: add
  - !run:
    exe: 'explorer.exe'
    wait: false

    # Disable Shared Experiences
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System'
    value: 'EnableCdp'
    data: '0'
    type: REG_DWORD

    # Show all tasks in Control Panel
  - !registryValue:
    path: 'HKLM\SOFTWARE\Classes\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'
    data: 'All Tasks'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Classes\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'
    value: 'InfoTip'
    data: 'View list of all Control Panel tasks'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Classes\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'
    value: 'System.ControlPanel.Category'
    data: '5'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Classes\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}\DefaultIcon'
    data: 'C:\Windows\System32\imageres.dll,-27'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Classes\CLSID\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}\Shell\Open\Command'
    data: 'explorer.exe shell:::{ED7BA470-8E54-465E-825C-99712043E01C}'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\NameSpace\{D15ED2E1-C75B-443c-BD7C-FC03B2F08C17}'
    data: 'All Tasks'
    type: REG_SZ

    # Disable notify about USB issues
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Shell\USB'
    value: 'NotifyOnUsbErrors'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Shell\USB'
    value: 'NotifyOnWeakCharger'
    data: '0'
    type: REG_DWORD

    # Disable automatic maintenance
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance'
    value: 'MaintenanceDisabled'
    data: '1'
    type: REG_DWORD

    # Disable scheduled system maintenance
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\ScheduledDiagnostics'
    value: 'EnabledExecution'
    data: '0'
    type: REG_DWORD

    # Do not reduce sounds while in a call
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio'
    value: 'UserDuckingPreference'
    data: '3'
    type: REG_DWORD

    # Do not show hidden and disconnected devices in mmsys.cpl
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio\DeviceCpl'
    value: 'ShowDisconnectedDevices'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Multimedia\Audio\DeviceCpl'
    value: 'ShowHiddenDevices'
    data: '0'
    type: REG_DWORD

    # Show removable drivers only in 'This PC' on the file explorer sidebar
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\DelegateFolders\{F5FB2C77-0E2F-4A16-A381-3E560C68BC83}'}
  - !registryKey: {path: 'HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\DelegateFolders\{F5FB2C77-0E2F-4A16-A381-3E560C68BC83}\{F5FB2C77-0E2F-4A16-A381-3E560C68BC83}'}

    # Remove network navigation pane from File Explorer
  - !registryValue:
    path: 'HKCR\CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\ShellFolder'
    value: 'Attributes'
    data: '2962489444'
    type: REG_DWORD

    # Remove 'Restore previous versions' from context menu and file' properties
  - !registryKey: {path: 'HKCR\AllFilesystemObjects\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Directory\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Drive\shellex\PropertySheetHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\AllFilesystemObjects\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Directory\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryKey: {path: 'HKCR\Drive\shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', value: 'NoPreviousVersionsPage', operation: delete}
  - !registryValue: {path: 'HKCU\SOFTWARE\Policies\Microsoft\PreviousVersions', value: 'DisableLocalPage', operation: delete}

    # Remove '- Shortcut' text added onto shortcuts
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'
    value: 'link'
    data: '00000000'
    type: REG_BINARY

    # Remove shortcut icon
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons'
    value: '29'
    data: 'C:\Windows\AtlasModules\Other\Blank.ico,0'
    type: REG_SZ

    # ------------------ Registry Portion END ------------------

    # Prevent Microsoft Edge (Chromium) from installing after updates
    # For future Windows Update support
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'DoNotUpdateToEdgeWithChromium', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'Install{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'Install{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'InstallDefault', type: REG_DWORD, data: '0'}

    # Fix no downloads folder bug
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{088e3905-0323-4b02-9826-5d99428e115f}', operation: add}

    # Remove SecurityHealthSystray startup item
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'SecurityHealth', operation: delete}

  - !writeStatus: {status: 'Setting profile pictures'}
  - !run:
    exeDir: true
    exe: 'PFP.cmd'
    weight: 20

  - !writeStatus: {status: 'Finalizing configuration'}
  - !run:
    exeDir: true
    exe: 'FINALIZE.cmd'
    weight: 100

    # Backup Atlas services & drivers after all modifications
  - !run: {exe: 'BACKUP2.cmd', exeDir: true}

  - !writeStatus: {status: "Cleaning up temp files & WinSxS"}
  - !cmd:
    exeDir: true
    command: 'DISM /Online /Cleanup-Image /StartComponentCleanup'
    weight: 30

    # Clean up temp folders and files
    # Cleanmgr does not clean these up as AME needs to be prevented from being deleted
  - !cmd:
    command: 'for /f %a in (''dir /b "%TEMP%" /a:-d'') do del /q "%TEMP%\%a"'
    weight: 10
    # Windows Temp folder
  - !cmd:
    command: 'del /f /s /q C:\Windows\Temp\*'
    weight: 10
    # The AME folder has to be excluded here, otherwise it will remove
    # the Playbook logs and cause issues with the AME Wizard
  - !cmd:
    command: 'for /f %a in (''dir /b "%TEMP%" /a:d ^| findstr /v /c:"AME"'') do rmdir /q /s "%TEMP%\%a"'
    weight: 10
