---
title: Configuration
description: Applies the Atlas configuration
privilege: TrustedInstaller
actions:
    # Prevent Microsoft Edge (Chromium) from installing after updates
    # For future Windows Update support
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'DoNotUpdateToEdgeWithChromium', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'Install{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}', type: REG_DWORD, data: '0'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'Install{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate', value: 'InstallDefault', type: REG_DWORD, data: '0'}

    # Fix no downloads folder bug
  - !registryKey: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{088e3905-0323-4b02-9826-5d99428e115f}', operation: add}

    # Remove SecurityHealthSystray startup item
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run', value: 'SecurityHealth', operation: delete}

    # Backup Atlas services & drivers after all modifications
  - !run: {exe: 'BACKUP2.cmd', exeDir: true}

  - !writeStatus: {status: "Cleaning up temp files & WinSxS"}
  - !cmd:
    exeDir: true
    command: 'DISM /Online /Cleanup-Image /StartComponentCleanup'
    weight: 30

    # Clean up temp folders and files
    # Cleanmgr does not clean these up as AME needs to be prevented from being deleted
  - !cmd:
    command: 'for /f %a in (''dir /b "%TEMP%" /a:-d'') do del /q "%TEMP%\%a"'
    weight: 10
    # Windows Temp folder
  - !cmd:
    command: 'del /f /s /q C:\Windows\Temp\*'
    weight: 10
    # The AME folder has to be excluded here, otherwise it will remove
    # the Playbook logs and cause issues with the AME Wizard
  - !cmd:
    command: 'for /f %a in (''dir /b "%TEMP%" /a:d ^| findstr /v /c:"AME"'') do rmdir /q /s "%TEMP%\%a"'
    weight: 10
