---
title: Add Theme
description: Adds and sets the Atlas themes by default
actions:
    # Copy files
  - !cmd:
    command: 'copy /y "Themes" "%windir%\Resources\Themes" > nul'
    exeDir: true
    wait: true

    # Apply theme file
  - !cmd:
    command: 'start "" "%windir%\Resources\Themes\atlas-v0.4.x-dark.theme"'
    wait: true
    runas: currentUserElevated
  - !run: {exe: 'timeout', args: '/t 4 /nobreak'}
  - !taskKill: {name: 'SystemSettings', ignoreErrors: true}
  - !taskKill: {name: 'control', ignoreErrors: true}

    # Applies Atlas lockscreen background
    # Also disables fun facts, tips, tricks, and more on lockscreen - only on Enterprise/Education
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization'
    value: 'LockScreenOverlaysDisabled'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'RotatingLockScreenEnabled'
    data: '0'
    type: REG_DWORD
  - !run:
    exe: 'THEME.cmd'
    exeDir: true
  - !powerShell:
    command: '& ".\AtlasModules\Scripts\LOCKSCREEN.ps1"'
    exeDir: true
    wait: true
    runas: currentUserElevated

    # Set Atlas theme as default for new users
  - !registryValue:
    path: 'HKCU\Software\Policies\Microsoft\Windows\Personalization'
    value: 'ThemeFile'
    data: '%windir%\Resources\Themes\atlas-v0.4.x-dark.theme'
    type: REG_SZ

    # For Windows 11, set recent theme selection
  - !powerShell:
    command: '.\AtlasModules\Scripts\newUsers.ps1 -ThemeMRU'
    exeDir: true
    wait: true
    builds: [ '>=22000' ]
