name: Create Atlas Playbook

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: |
            echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Validate YAML files
        run: 'yamllint -d "{extends: relaxed, rules: {line-length: disable, new-line-at-end-of-file: disable, trailing-spaces: disable}}" src/.'

      - name: Create playbook
        run: |
            cd src
            sed -i '/<ProductCode>/d' playbook.conf
            sed -i 's|<Description>.*<\/Description>|<Description>Experimental testing version of the Atlas playbook, build from GitHub Actions from commit ${\{ steps.vars.outputs.sha_short \}}. Be aware of these builds being potentially unstable and buggy!</Description>|g' playbook.conf
            zip -r "Atlas Playbook ${{ steps.vars.outputs.sha_short }}.apbx" . -x "Release ZIP/*"
            mv "Atlas Playbook ${{ steps.vars.outputs.sha_short }}.apbx" "Release ZIP"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Atlas Playbook
          path: |
            src/Release ZIP/*
          if-no-files-found: error
